-- Generates the schema for the website H2 DB
-- Use command: runscript from 'create-website-db.sql' to generate DB tables
-- For exporting schemas run: script to 'create-website-db.sql'
;
CREATE SEQUENCE "PUBLIC"."BLOG_SEQ" START WITH 1;
CREATE SEQUENCE "PUBLIC"."TOPIC_SEQ" START WITH 1;
CREATE SEQUENCE "PUBLIC"."BLOG_TOPIC_SEQ" START WITH 1;
CREATE SEQUENCE "PUBLIC"."STATIC_FILE_SEQ" START WITH 1;
CREATE CACHED TABLE "PUBLIC"."BLOG"(
    "ID" BIGINT NOT NULL,
    "CREATED" TIMESTAMP(6) NOT NULL,
    "FILE_NAME" CHARACTER VARYING(255) NOT NULL,
    "HASH" CHARACTER VARYING(255) NOT NULL,
    "TITLE" CHARACTER VARYING(255) NOT NULL,
    "UPDATED" TIMESTAMP(6)
);
ALTER TABLE "PUBLIC"."BLOG" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("ID");
CREATE CACHED TABLE "PUBLIC"."BLOG_TOPIC"(
    "BLOG_ID" BIGINT NOT NULL,
    "ID" BIGINT NOT NULL,
    "TOPIC_ID" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."BLOG_TOPIC" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_6" PRIMARY KEY("ID");
CREATE CACHED TABLE "PUBLIC"."TOPIC"(
    "ID" BIGINT NOT NULL,
    "NAME" CHARACTER VARYING(255) NOT NULL
);
ALTER TABLE "PUBLIC"."TOPIC" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4C" PRIMARY KEY("ID");
CREATE CACHED TABLE "PUBLIC"."STATIC_FILE"(
    "ID" BIGINT NOT NULL,
    "HASH" CHARACTER VARYING(255) NOT NULL,
    "MODIFIED" TIMESTAMP(6) NOT NULL,
    "NAME" CHARACTER VARYING(255) NOT NULL,
    "TYPE" ENUM('CSS', 'IMAGE') NOT NULL
);
ALTER TABLE "PUBLIC"."STATIC_FILE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_B" PRIMARY KEY("ID");
ALTER TABLE "PUBLIC"."BLOG" ADD CONSTRAINT "PUBLIC"."UKRNROU1M94MUCGT39EPCW8OV59" UNIQUE NULLS DISTINCT ("TITLE");
ALTER TABLE "PUBLIC"."BLOG" ADD CONSTRAINT "PUBLIC"."UKSF1PVRAKVQMVSD6601YJ154IQ" UNIQUE NULLS DISTINCT ("FILE_NAME");
ALTER TABLE "PUBLIC"."TOPIC" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" UNIQUE NULLS DISTINCT ("NAME");
ALTER TABLE "PUBLIC"."STATIC_FILE" ADD CONSTRAINT "PUBLIC"."UK46VFLF26WY2GO80AIDYVPIUI3" UNIQUE NULLS DISTINCT ("NAME");
ALTER TABLE "PUBLIC"."BLOG_TOPIC" ADD CONSTRAINT "PUBLIC"."FKP9PN3XQE5KUYOLD2IJH0RVOWL" FOREIGN KEY("BLOG_ID") REFERENCES "PUBLIC"."BLOG"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."BLOG_TOPIC" ADD CONSTRAINT "PUBLIC"."FKEPKON8VFEAYO4M7V3KOWWAXEG" FOREIGN KEY("TOPIC_ID") REFERENCES "PUBLIC"."TOPIC"("ID") NOCHECK;