# Custom application options
application.cache-control=public, max-age=0, must-revalidate
application.blogs-directory=blogs
application.images-directory=static/images
application.css=static/style.min.css
application.javascript=static/script.min.js

# Packaging options
quarkus.package.jar.add-runner-suffix=false

# Disable devservices
quarkus.devservices.enabled=false

# Markdown render cache
quarkus.cache.caffeine."blog-html".maximum-size=100
quarkus.cache.caffeine."blog-html".expire-after-access=4h

# HTTP options
quarkus.http.port=8080
quarkus.http.header."Server".path=/*
quarkus.http.header."Server".value=Potato
quarkus.http.header."Host".path=/*
quarkus.http.header."Host".value=Me
quarkus.http.header."X-Powered-By".path=/*
quarkus.http.header."X-Powered-By".value=Potato
quarkus.http.header."From".path=/*
quarkus.http.header."From".value=A lovely chap
